services:
  postgres:
    container_name: postgres_learning_network
    image: postgres:alpine3.19
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  eureka-server:
    image: macchiato23/filn-discovery:0.0.1-SNAPSHOT
    container_name: eureka-filn
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

#  apigw:
#    image:  macchiato23/filn-apigw:0.0.1-SNAPSHOT
#    container_name: apigw_filn
#    ports:
#      - "8080:8080"
#    depends_on:
#      - eureka-server

networks:
  postgres:
    driver: bridge

volumes:
  postgres: